//REGEN_FILEHEADING
//REGEN_FILEHEADING

extern HANDLE   hInst;
// Defines for menu item IDs
#define   IDM_ABOUT                           101
#define   IDM_EXIT                            102
#define   IDM_CLEAR                           103
#define   IDM_HELP                            104
#define   IDM_FROMCB						  105
//REGEN_HEADER
//REGEN_HEADER

// Function prototypes for dialog and subdialog modules
